parameters:
    url.manager.redirect_route: redirect
    
services:
    form.type.url_shorten:
        class: AppBundle\Form\Type\UrlShortenType
        tags:
            - { name: form.type, alias: url_shorten }
            
    url.manager:
        class: AppBundle\UrlManager\UrlManager
        arguments:
            - @doctrine.orm.entity_manager
            - @router
            - %url.manager.redirect_route%